### ISSUE TITLE
connect endpoints to campaign page functionality

### ISSUE THREAD

**Issue by AhmedBarre1** [4cecoder/drip-campaign#8]
setup put requests for campaigns page to change campaign details setup simple forms if you need it inorder to update values ill make the forms better just do the bare minimum to reach functionality

**Comment by 4cecoder** [comment]
Recent push to main adds more functionality to try get the api working on campaign page

**Comment by 4cecoder** [comment]
![image](https://github.com/4cecoder/drip-campaign/assets/88108711/bda73714-ae2d-476e-b365-2eac5395c3df)
